### ISSUE TITLE
Can't compile with png feature

### ISSUE THREAD

**Issue by lucascompython** [etemesi254/zune-image#282]
Im on Linux, when i try to compile with the `png` feature I get the following error:
```
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `exif`
  --> /home/lucas/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zune-image-0.4.15/src/codecs/png.rs:13:5
   |
13 | use exif::experimental::Writer;
   |     ^^^^ use of unresolved module or unlinked crate `exif`
   |
   = help: if you wanted to use a crate named `exif`, use `cargo add exif` to add it to your `Cargo.toml`

error[E0282]: type annotations needed for `std::io::Cursor<Vec<_>>`
   --> /home/lucas/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zune-image-0.4.15/src/codecs/png.rs:176:13
    |
176 |         let mut buf = std::io::Cursor::new(vec![]);
    |             ^^^^^^^   ---------------------------- type must be known at this point
    |
help: consider giving `buf` an explicit type, where the placeholders `_` are specified
    |
176 |         let mut buf: std::io::Cursor<Vec<_>> = std::io::Cursor::new(vec![]);
    |                    +++++++++++++++++++++++++

   Compiling palette v0.6.1
Some errors have detailed explanations: E0282, E0433.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `zune-image` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by etemesi254** [comment]
A question, is it okay if you try the `0.5` branch (it's rc in crates io ) it may have a fix.

I made the mistake of not branching when i started the 0.5 branch where i do such fixes ( unless it's jpeg which has a 0.4 branch due to it being used in image-rs
)

**Comment by lucascompython** [comment]
It compiles with `0.5`, thanks!

I have another question, how can I apply a watermark where the watermark is smaller than the image? 
`zune_imageprocs::blend::Blend` expects both images to have the same dimensions.

**Comment by etemesi254** [comment]
`Composite` will be the function for that.

E.g example

```rust
        let mut source_image = Image::from_fn(
            100usize,
            100usize,
            zune_core::colorspace::ColorSpace::RGBA,
            |_y, _x, pixels| {
                pixels[0] = 255u8;
                pixels[1] = 255u8;
                pixels[2] = 255u8;
                pixels[3] = 255u8;
            }
        );

        let  watermark = Image::from_fn(
            30usize,
            50usize,
            zune_core::colorspace::ColorSpace::RGBA,
            |_y, _x, pixels| {
                pixels[0] = 0u8;
                pixels[1] = 0u8;
                pixels[2] = 0u8;
                pixels[3] = 0xffu8;
            }
        );

        let composite = Composite::new(&watermark, CompositeMethod::Over, (4usize, 6usize));

        composite.execute(&mut source_image).unwrap();

        source_image.save("composite.png").unwrap();
```

Generates

![Image](https://github.com/user-attachments/assets/414c7bbb-22b3-426e-84b9-01621498b3cc)


There is also a gravity option, which specifies a specific corner, e.g center, top left etc you use `Composite::new_gravity`

**Comment by lucascompython** [comment]
Thanks, that's seems to be it, although I still have another problem...
My source images are `jpeg` and the watermark is `png`, when I try to use `Composite`, I get the following error:
```
thread '<unnamed>' panicked at src/main.rs:592:37:
called `Result::unwrap()` on an `Err` value: Image colorspace does not match for composite src image = RGBA, dst_image = RGB
```

Thanks in advance
