### ISSUE TITLE
avx2 build error: _mm256_add_epi16 is unsafe

### ISSUE THREAD

**Issue by tim-murphy** [etemesi254/zune-image#325]
Looks like the error was introduced in 78ed595. I'm running cargo 1.86.0 on Linux Mint 20.

```
   Compiling zune-jpeg v0.5.7
error[E0133]: call to unsafe function `std::arch::x86_64::_mm256_set1_epi16` is unsafe and requires unsafe function or block
  --> /home/tim/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zune-jpeg-0.5.7/src/upsampler/avx2.rs:36:19
   |
36 |     let v_three = _mm256_set1_epi16(3);
   |                   ^^^^^^^^^^^^^^^^^^^^ call to unsafe function
   |
   = note: consult the function's documentation for information on how to avoid undefined behavior
```

There are many of these errors all from this one file. It looks like they all originated from the same commit.

To reproduce:
1. `cargo init`
2. `cargo add zune-jpeg`
3. `cargo build`

Thanks.

**Comment by tim-murphy** [comment]
Upgraded to Cargo 1.92.0 which resolved the issue.
